name: Android build

on: [workflow_dispatch, push]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm64", "arm32", "x86", "x64" ]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: |
            8
            25

    - name: Build for Android ${{matrix.arch}}
      run: |
        export JAVA8_HOME=$JAVA_HOME_8_${{runner.arch}}
        export LWJGL_BUILD_ARCH=${{matrix.arch}}
        bash ci_build_android.bash

    - name: Upload modules release output
      if: ${{matrix.arch == 'arm64'}} # Only upload this once
      uses: actions/upload-artifact@v4
      with:
        name: lwjgl-3.4.1-android-modules
        path: bin/RELEASE

    - name: Upload native build output
      uses: actions/upload-artifact@v4
      with:
        name: lwjgl-3.4.1-android-natives-${{matrix.arch}}
        path: bin/out
  aar:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: false
        gradle-version: "8.14.3"
    - name: Download built native artifacts (arm64)
      uses: actions/download-artifact@v8
      with:
          name: lwjgl-3.4.1-android-natives-arm64
          path: .github/workflows/android/assets/components/lwjgl-3.4.1-natives/arm64-v8a
    - name: Download built native artifacts (arm32)
      uses: actions/download-artifact@v8
      with:
          name: lwjgl-3.4.1-android-natives-arm32
          path: .github/workflows/android/assets/components/lwjgl-3.4.1-natives/armeabi-v7a
    - name: Download built native artifacts (x64)
      uses: actions/download-artifact@v8
      with:
          name: lwjgl-3.4.1-android-natives-x64
          path: .github/workflows/android/assets/components/lwjgl-3.4.1-natives/x86_64
    - name: Download built native artifacts (x86)
      uses: actions/download-artifact@v8
      with:
          name: lwjgl-3.4.1-android-natives-x86
          path: .github/workflows/android/assets/components/lwjgl-3.4.1-natives/x86
    - name: Compile into one AAR
      run: |
          cd $GITHUB_WORKSPACE/.github/workflows/android
          gradle assembleRelease
    - name: Upload AAR
      uses: actions/upload-artifact@v4
      with: 
          name: lwjgl-3.4.1-android-natives-aar
          path: .github/workflows/android/build/outputs/aar/lwjgl-3.4.1-natives-release.aar
